### ISSUE TITLE
trans lightgbm.txt to lightgbm.pmml failed.

### ISSUE THREAD

**Issue by yuzhixing** [jpmml/jpmml-lightgbm#43] opened 2020-11-22 06:27 UTC
It's a real lightgbm model file, but trans to pmml failed.
because some value of section is null, such as “left_child”, then NPE will happen in parseStringArray of LightGBMUtil lined 100。

the model builed by lightgbm version 3.0.0。

how can i do it?

**Comment by vruusmann** [comment] 2020-11-22 07:38
Closing as exact duplicate of #41.

Was fixed yesterday. Please upgrade.

**Closed by vruusmann** 2020-11-22 07:38 UTC

**Comment by vruusmann** [comment] 2020-11-22 07:40
> It's a real lightgbm model file

Can be a real LightGBM model file, but when there are empty tree elements inside the tree ensemble, then it means that your model training process was incorrectly parameterized (typically, specified an unreasonably large `n_estimators` value).

**Comment by yuzhixing** [comment] 2020-11-22 08:27
thanks
