### ISSUE TITLE
Error with NullPointerException

### ISSUE THREAD

**Issue by lyliu** [jpmml/jpmml-lightgbm#45] opened 2020-11-27 01:58 UTC
Hi,
When I run "java -jar target/jpmml-lightgbm-executable-1.3-SNAPSHOT.jar --lgbm-input model.txt --pmml-output lightgbm.pmml", there was an error with the following information:
```
Exception in thread "main" java.lang.NullPointerException
	at org.jpmml.lightgbm.LightGBMUtil.parseStringArray(LightGBMUtil.java:100)
	at org.jpmml.lightgbm.LightGBMUtil.parseIntArray(LightGBMUtil.java:111)
	at org.jpmml.lightgbm.Section.getIntArray(Section.java:62)
	at org.jpmml.lightgbm.Tree.load(Tree.java:78)
	at org.jpmml.lightgbm.GBDT.load(GBDT.java:119)
	at org.jpmml.lightgbm.LightGBMUtil.loadGBDT(LightGBMUtil.java:53)
	at org.jpmml.lightgbm.LightGBMUtil.loadGBDT(LightGBMUtil.java:45)
	at org.jpmml.lightgbm.Main.run(Main.java:141)
	at org.jpmml.lightgbm.Main.main(Main.java:134)
```
 so, how to solve it?

**Comment by vruusmann** [comment] 2020-11-27 05:56
Duplicate of #41

> how to solve it?

You solve it by upgrading to the latest version.

**Closed by vruusmann** 2020-11-27 05:56 UTC
