### ISSUE TITLE
An error occurred when the dataset contains string features

### ISSUE THREAD

**Issue by Archmagegck** [jpmml/jpmml-lightgbm#47] opened 2021-02-19 09:27 UTC
My dataset contains some string features, and I used _StringIndexer + OneHotEncoder_ to encode them. When I put the StringIndexers, OneHotEncoders, VectorAssembler, and LightGBM in a pipeline, and fit the pipeline, everything is ok.
![image](https://user-images.githubusercontent.com/8872911/108484791-2d641180-72d7-11eb-815b-ce9b68730372.png)
But, when I want to saved the pipeline into PMML, an error occurred. The error log is: Py4JJavaError: An error occurred while calling o353581.buildFile.
: java.lang.IllegalArgumentException: Field userinfov4_worktype has data type string
![image](https://user-images.githubusercontent.com/8872911/108485175-977cb680-72d7-11eb-912d-97f990484de9.png)

userinfov4_worktype is one of the string features. 
I used jpmml-lightgbm-1.2.13

**Comment by vruusmann** [comment] 2021-02-19 09:35
> I used jpmml-lightgbm-1.2.13

According to the posted stack trace, this exception is raised via/by the `org.jpmml-sparkml.BoosterUtil` utility class.

This class is not part of the JPMML ecosystem. Please refer to that person/organization who is responsible for that crap (and is violating my IP rights with respect to the JPMML trademark, and generic JPMML license terms and conditions).

**Comment by vruusmann** [comment] 2021-02-19 09:39
Closing as exact duplicate of https://github.com/jpmml/jpmml-sparkml/issues/107

@Archmagegck Please stop from spamming the JPMML organization by opening/closing issues randomly.

**Closed by vruusmann** 2021-02-19 09:39 UTC

**Comment by Archmagegck** [comment] 2021-02-19 10:19
I'm very sorry that I didn't look at the source of the problem carefully. Sorry to disturb you. Thank you for your advice.
