### ISSUE TITLE
fail for : java.lang.NumberFormatException: For input string: "inf"

### ISSUE THREAD

**Issue by jefftan83** [jpmml/jpmml-lightgbm#49] opened 2021-06-20 13:00 UTC
fail for 
```
java.lang.NumberFormatException: For input string: "inf"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:538)
        at java.lang.Double.valueOf(Double.java:502)
        at org.jpmml.lightgbm.LightGBMUtil.parseInterval(LightGBMUtil.java:213)
```

**Comment by vruusmann** [comment] 2021-06-20 15:38
Closing as exact duplicate of https://github.com/jpmml/jpmml-lightgbm/issues/48

The question remains - how are you able to generate `inf` as continuous feature bounds? I'm using the latest LightGBM version, and I can't make it happen.

I can't fix an error that I can't reproduce locally.

**Closed** 2021-06-24 09:39 UTC
